# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_Fk7ZcVo0O_F_petLsr5t43yTr4wv9V
"""

from flask import Flask, request, render_template, jsonify
import joblib
import pandas as pd
import os

app = Flask(__name__)

# Load the model
model = joblib.load('titanic_survival_model.pkl')

# Load feature columns if exists
try:
    feature_columns = joblib.load('feature_columns.pkl')
except:
    feature_columns = None

# Mapping for categorical variables (must match your training)
sex_map = {'male': 1, 'female': 0}
embarked_map = {'C': 0, 'Q': 1, 'S': 2}
title_map = {'Mr': 0, 'Miss': 1, 'Mrs': 2, 'Master': 3, 'Rare': 4}

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        try:
            # Get data from the form
            data = {
                'Pclass': int(request.form['Pclass']),
                'Sex': request.form['Sex'],
                'Age': float(request.form['Age']),
                'SibSp': int(request.form['SibSp']),
                'Parch': int(request.form['Parch']),
                'Fare': float(request.form['Fare']),
                'Embarked': request.form['Embarked'],
                'Title': request.form.get('Title', 'Mr'),
                'Has_Cabin': int(request.form.get('Has_Cabin', 0)),
                'FamilySize': int(request.form.get('FamilySize', 1)),
                'IsAlone': int(request.form.get('IsAlone', 1))
            }

            input_df = pd.DataFrame([data])

            # Encode categorical features same as your notebook
            input_df['Sex'] = input_df['Sex'].map(sex_map)
            input_df['Embarked'] = input_df['Embarked'].map(embarked_map)
            input_df['Title'] = input_df['Title'].map(title_map)

            # Make sure columns order matches training
            if feature_columns:
                input_df = input_df.reindex(columns=feature_columns, fill_value=0)

            # Make prediction
            prediction = model.predict(input_df)[0]
            probability = round(model.predict_proba(input_df)[0][1] * 100, 2)

            result = "✅ Survived" if prediction == 1 else "❌ Did Not Survive"

            return render_template('index.html',
                                   prediction=result,
                                   probability=probability)

        except Exception as e:
            return f"Error: {str(e)}"

    # Show the form when page loads
    return render_template('index.html', prediction=None)

if __name__ == '__main__':
    app.run(debug=False)